name: Run tests

on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  check_sha:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
      sha: ${{ steps.get_sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: dagargo/overwitch
      - id: get_sha
        name: get latest_commit
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours" ${{ steps.get_sha.outputs.sha }} && echo "{should_run}=false"  >> "$GITHUB_OUTPUT"

  release-nightly:
    needs: check_sha
    if: ${{ needs.check_sha.outputs.should_run != 'false' }}
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Clone Overwitch
      uses: actions/checkout@v3
      with:
        repository: dagargo/overwitch
    - name: install dependencies
      run: |
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install automake libtool libusb-1.0-0-dev libjack-jackd2-dev libsamplerate0-dev libsndfile1-dev autopoint gettext libjson-glib-dev libgtk-4-dev libsystemd-dev
          sudo apt-get -y --no-install-recommends install libcunit1-dev
    - name: autoreconf
      run: autoreconf --install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make clean distcheck
    - name: create tag
      id: create_tag
      run: |
        git tag {{ needs.check_sha.outputs.sha }}
        git push origin {{ needs.check_sha.outputs.sha }}
    - name: create nightly release
      uses: softprops/action-gh-release@v2
      with:
        files: overwitch-*.tar.gz
        name: "$(date +'%Y-%m-%d')-{{ needs.check_sha.outputs.sha }}"
        tag_name: "{{ needs.check_sha.outputs.sha }}"